[project]
name = "mcp-server-aws-ecs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.38.13",
    "httpx>=0.28.1",
    "mcp[cli]>=1.8.0",
]
